# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TattooFinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod "CenteredCollectionView"
  pod 'SDWebImage', '~> 4.0'

end
